language: ruby
rvm:
  - 2.0.0
  - 2.1.1
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

addons:
  code_climate:
    repo_token: d08e7df3b9976d121092b57a1e5e57748e941038b39b8a7107fe1c16e813cd77

script: 'bundle exec rake spec'
